### ISSUE TITLE
Create a Code of Conduct

### ISSUE THREAD

**Issue by larister** [asyncjs/async-website#128]
Perhaps adapt http://confcodeofconduct.com, and announce why we're doing that - also ensure we have a point of conduct (Ali and Rosa volunteered)

**Comment by larister** [comment]
From @Finetuned (who couldn't comment because github):

Had a suggestion from @cybergazz that we should look at http://geekfeminism.org/about/code-of-conduct/
They have a modifiable policy http://geekfeminism.wikia.com/wiki/Community_anti-harassment/Policy

**Comment by larister** [comment]
From @yanneves:

Excellent, that's really helpful, the one I noted previously from FFConf (and JSConf) is at http://confcodeofconduct.com

**Comment by Finetuned** [comment]
test

**Comment by Finetuned** [comment]
test
