### ISSUE TITLE
"Previous Event" and "Following Event" are mismatched

### ISSUE THREAD

**Issue by yanneves** [asyncjs/async-website#178]
On an event page, future events are displayed under the "Previous Event" heading, and past events under the "Following Event" heading. These should be the other way round.

<img width="735" alt="screen shot 2017-12-31 at 15 52 15" src="https://user-images.githubusercontent.com/1331877/34462762-c9d71160-ee42-11e7-8246-2ceab69a1be4.png">
Example from https://asyncjs.com/firebase/

**Comment by rumshenoy** [comment]
Hi! I would like to work on this.

**Comment by yanneves** [comment]
Hey, thanks, dive in! `_layouts/event.html` would be the place to start

I think because we display events in date descending order, `next` is actually the previous event chronologically, and vice versa for `previous`
